-- =============================================
-- 1. CLEAN UP (Xóa bảng cũ nếu muốn reset)
-- Lưu ý: Chỉ chạy phần này nếu muốn xóa sạch dữ liệu làm lại từ đầu
-- =============================================
/*
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.order_items CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.book_authors CASCADE;
DROP TABLE IF EXISTS public.book_categories CASCADE;
DROP TABLE IF EXISTS public.books CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.authors CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TYPE IF EXISTS user_role;
DROP TYPE IF EXISTS book_status;
DROP TYPE IF EXISTS order_status;
*/

-- =============================================
-- 2. ENUM TYPES (Định nghĩa các trạng thái)
-- =============================================
CREATE TYPE user_role AS ENUM ('customer', 'seller', 'admin');
CREATE TYPE book_status AS ENUM ('pending', 'approved', 'rejected', 'hidden');
CREATE TYPE order_status AS ENUM ('pending', 'confirmed', 'shipping', 'delivered', 'cancelled');

-- =============================================
-- 3. TABLES (Tạo bảng)
-- =============================================

-- 3.1 Profiles (Mở rộng từ auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT,
  full_name TEXT,
  avatar_url TEXT,
  phone_number TEXT,
  address TEXT,
  role user_role DEFAULT 'customer',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3.2 Categories (Thể loại sách)
CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE, -- URL thân thiện (vd: trinh-tham)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3.3 Authors (Tác giả)
CREATE TABLE public.authors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  bio TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3.4 Books (Sách)
CREATE TABLE public.books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id UUID REFERENCES public.profiles(id) NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  price DECIMAL(12, 0) NOT NULL CHECK (price >= 0),
  stock_quantity INT DEFAULT 0 CHECK (stock_quantity >= 0),
  cover_image_url TEXT,
  status book_status DEFAULT 'pending', -- Cần Admin duyệt
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3.5 Bảng trung gian Sách - Tác giả (N-N)
CREATE TABLE public.book_authors (
  book_id BIGINT REFERENCES public.books(id) ON DELETE CASCADE,
  author_id BIGINT REFERENCES public.authors(id) ON DELETE CASCADE,
  PRIMARY KEY (book_id, author_id)
);

-- 3.6 Bảng trung gian Sách - Thể loại (N-N)
CREATE TABLE public.book_categories (
  book_id BIGINT REFERENCES public.books(id) ON DELETE CASCADE,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE CASCADE,
  PRIMARY KEY (book_id, category_id)
);

-- 3.7 Orders (Đơn hàng - Header)
CREATE TABLE public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id UUID REFERENCES public.profiles(id) NOT NULL,
  total_amount DECIMAL(12, 0) NOT NULL,
  status order_status DEFAULT 'pending',
  shipping_address TEXT NOT NULL,
  shipping_phone TEXT NOT NULL,
  note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3.8 Order Items (Chi tiết đơn hàng)
CREATE TABLE public.order_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT REFERENCES public.orders(id) ON DELETE CASCADE,
  book_id BIGINT REFERENCES public.books(id), -- Không cascade để giữ lịch sử nếu xóa sách
  seller_id UUID REFERENCES public.profiles(id), -- Để Seller dễ query
  quantity INT NOT NULL CHECK (quantity > 0),
  price_at_purchase DECIMAL(12, 0) NOT NULL, -- Lưu giá tại thời điểm mua
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3.9 Cart Items (Giỏ hàng)
CREATE TABLE public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  book_id BIGINT REFERENCES public.books(id) ON DELETE CASCADE,
  quantity INT DEFAULT 1 CHECK (quantity > 0),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, book_id)
);

-- 3.10 Reviews (Đánh giá)
CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT REFERENCES public.books(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
  rating INT CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(book_id, user_id)
);

-- =============================================
-- 4. ROW LEVEL SECURITY (RLS) - BẢO MẬT
-- =============================================

-- Bật RLS cho tất cả bảng
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.books ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- 4.1 Chính sách Profiles
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- 4.2 Chính sách Books
CREATE POLICY "Everyone can view approved books" ON public.books FOR SELECT USING (status = 'approved' OR auth.uid() = seller_id);
CREATE POLICY "Sellers can insert books" ON public.books FOR INSERT WITH CHECK ((SELECT role FROM public.profiles WHERE id = auth.uid()) = 'seller');
CREATE POLICY "Sellers can update own books" ON public.books FOR UPDATE USING (auth.uid() = seller_id);
CREATE POLICY "Sellers can delete own books" ON public.books FOR DELETE USING (auth.uid() = seller_id);

-- 4.3 Chính sách Orders
CREATE POLICY "Users view own orders" ON public.orders FOR SELECT USING (auth.uid() = customer_id);
CREATE POLICY "Users insert orders" ON public.orders FOR INSERT WITH CHECK (auth.uid() = customer_id);

-- 4.4 Chính sách Order Items (Seller xem được item mình bán, Customer xem được item mình mua)
CREATE POLICY "View order items" ON public.order_items FOR SELECT USING (
  seller_id = auth.uid() OR 
  EXISTS (SELECT 1 FROM public.orders WHERE orders.id = order_items.order_id AND orders.customer_id = auth.uid())
);

-- 4.5 Chính sách Cart & Reviews
CREATE POLICY "Manage own cart" ON public.cart_items FOR ALL USING (auth.uid() = user_id);
CREATE POLICY "View reviews" ON public.reviews FOR SELECT USING (true);
CREATE POLICY "Create reviews" ON public.reviews FOR INSERT WITH CHECK (auth.uid() = user_id);

-- =============================================
-- 5. TRIGGERS & FUNCTIONS (Tự động hóa)
-- =============================================

-- Hàm tự động tạo Profile khi có User mới đăng ký qua Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, avatar_url)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Gán Trigger vào bảng auth.users
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =============================================
-- 6. STORAGE (Tạo Bucket cho ảnh bìa)
-- =============================================
-- Insert vào bảng buckets của Supabase (nếu chưa có)
INSERT INTO storage.buckets (id, name, public) 
VALUES ('book-covers', 'book-covers', true)
ON CONFLICT (id) DO NOTHING;

-- Policy cho Storage: Ai cũng được xem, nhưng chỉ User đã login mới được Upload
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'book-covers' );
CREATE POLICY "Authenticated Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'book-covers' AND auth.role() = 'authenticated' );

-- =============================================
-- 7. SEED DATA (Dữ liệu mẫu để test)
-- =============================================
INSERT INTO public.categories (name, slug) VALUES 
('Tiểu thuyết', 'tieu-thuyet'),
('Kinh tế', 'kinh-te'),
('Khoa học viễn tưởng', 'khoa-hoc-vien-tuong'),
('Tâm lý - Kỹ năng sống', 'tam-ly-ky-nang'),
('Truyện tranh (Manga)', 'manga');

INSERT INTO public.authors (name, bio) VALUES
('Nguyễn Nhật Ánh', 'Nhà văn chuyên viết cho thanh thiếu niên.'),
('J.K. Rowling', 'Tác giả bộ truyện Harry Potter nổi tiếng.'),
('Haruki Murakami', 'Nhà văn Nhật Bản đương đại.');